version: 1.0.0

sources:
  - name: raw
    description: Staging tables in Snowflake
    schema: raw
    tables:
      - name: customers
        identifier: CUSTOMERS
      - name: agents
        identifier: AGENTS
      - name: call_logs
        identifier: CALL_LOGS
      - name: sm_complaints
        identifier: SM_COMPLAINTS
      - name: web_complaints
        identifier: WEB_COMPLAINTS
        loaded_at_field: loaded_at
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 60 #to fix
            period: hour
          
          
          
